name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akaihola/darker@1.3.2
        with:
          options: "--check --verbose"
          src: "./"
          version: "1.3.2"
