name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Getting Python
      - uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.8
          
      - name: Installing Depends
        run: pip install darker
        
      - name: Using Darker
        run: python -m darker .
